# -*- coding: utf-8 -*-
"""
/***************************************************************************
 load_point
                                 A QGIS plugin
 load_point
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-05-14
        copyright            : (C) 2021 by Fish
        email                : h38604@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load load_point class from file load_point.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .load_point import load_point
    return load_point(iface)
